name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Check eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "functions/eslint_report.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: functions/eslint_report.json
